name: coresets-bench
channels:
  - conda-forge
dependencies:
  - python=3.8
  - click=8.0.1
  - scikit-learn=0.24.2
  - pandas=1.3.0
  - jupyterlab=3.0.16
  - seaborn=0.11.1
  - tqdm=4.61.2
  - psutil=5.8.0
  - scipy=1.7.0
  - h5py=3.3.0
